### ISSUE TITLE
One of the light-tree controllers is dead

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#23]
John Matthews reports that it was working during set up Thursday night but then stopped working.  We verified that the power was getting to it (the power cord had an orange light).  We tried plugging into another outlet without an extension cord.  Symptoms: No LEDs or lights or indicators when turned on and off.  Potential issue: the power cord existing the control box seems to be missing insulation near the entry point; perhaps it got pulled out and disconnected internally?

It is currently stored in the back of the lighting cabinet at Woods; the front one is the one that still works.

**Comment by michellestith** [comment]
We are shifting to using the school equipment, so for now we will not be repairing the tree.
