### ISSUE TITLE
Speaker stand at woods slipping

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#29]
We may need to drill out a hole and insert a peg at the right height. Should do this to both

**Comment by michellestith** [comment]
Russ if you are comfortable doing this one, go ahead and complete.  Mark and I won't be at the woods location for a couple weeks.

**Comment by russell-taylor** [comment]
Purchased a couple of 1/4" 1-3/4" pins and will put them in my cordless drill bag by the back door.  Tried to get scheduled for sound at Woods this Sunday.
