### ISSUE TITLE
Stripped tightener in On Stage Stands stand at Woods

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#33]
Tried getting a 1/4-20 hand-tightening bolt and nut, but the nut is slightly too large to fit into the fastener.  That was the closest fit they had at Lowes.  Will try purchasing from the manufacturer or finding the closest metric size and ordering online.

**Comment by russell-taylor** [comment]
It is an MS7701TB.  We need the leg housing knob, part number 40119.  Ideally, we'd also like the matching nut but that is not listed on the parts list.  Item total $1.75, freight $7.50... ordering 3 of them for same freight charge.  Order reference #1147200, to appear as "The Music People Inc" on the statement.  Can contact them at CS@musicpeopleinc.com with issues.

**Comment by michellestith** [comment]
Thanks, Russ.

**Comment by russell-taylor** [comment]
Parts arrived.  Using one of them fixed the stand.  Will drop it and the spares off at Woods after church on Sunday or hand it to someone in P'Boro for transport (I'm running sound in Pittsboro).

**Comment by russell-taylor** [comment]
Gave to Curtis to bring to Woods tomorrow.
