### ISSUE TITLE
1/4 to 1/8 cable for Pittsboro and woods

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#37]
To be ready for instruments that have 1/8 connectors to plug into direct box.

**Comment by russell-taylor** [comment]
Purchased one from Amazon to see if it works better in terms of reliable connection than the ones we have.  If so, will order more.

**Comment by russell-taylor** [comment]
Plan to bring one to try out at woods on Sunday then will purchase more if it works well

**Comment by russell-taylor** [comment]
When we tried it out on one of the monitors for the electric guitar, it behaved the same way as the original ones that we purchased.  Looks like either yet another kind is needed or there is something else going on.

**Comment by michellestith** [comment]
ok,I got one more cable to try...
-m

**Comment by russell-taylor** [comment]
The new cable that Michelle got worked for Tim when his cable was not. We have one more for Pittsboro.

**Comment by russell-taylor** [comment]
A box of them showed up in Pboro.  Will try replacing the cables and report back.

**Comment by russell-taylor** [comment]
Let Damian know to distribute them and collect the old cables to bring off-site, assuming the new ones work as well as the first one did.
