### ISSUE TITLE
Order AA batteries for Pittsboro

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#4]
We only have one box left after sending one to Woods

**Comment by russell-taylor** [comment]
Ordered on 3/12 to arrive by 3/14.  Will need to hand them off to someone to take to Pittsboro.

**Comment by russell-taylor** [comment]
Michelle is bringing them

**Comment by russell-taylor** [comment]
Michelle, have these arrived?  If so, we can go ahead and close this issue.  Thanks!

**Comment by michellestith** [comment]
Yes I brought them there Thursday
