### ISSUE TITLE
Need 3 new power strips for woods

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#53]

**Comment by russell-taylor** [comment]
The brand that we are using seems to be failing quite frequently.  Find another that is highly recommended, which has long power cords, and purchase these instead.

**Comment by russell-taylor** [comment]
Ordered 4 15' cord versions with high ratings.  To arrive Tuesday at my house.

**Comment by michellestith** [comment]
Can we put a sticker with Chatham Community Church and the date purchased
on them?  I can come by on Sunday with the label maker.
-m

**Comment by russell-taylor** [comment]
Great idea.  If you want to do that ahead of time I can leave them on my porch.  Otherwise I'll plan to drop them by Woods around 7:35 next Sunday.

**Comment by michellestith** [comment]
We'll just do it next Sunday at Woods, thanks.
