### ISSUE TITLE
Purchase headphones for Pittsboro

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#55]
One of them broke

**Comment by michellestith** [comment]
Thank you. Is this the sound tech’s headphones or musicians’?

Are you able to purchase or do you want me to?

**Comment by russell-taylor** [comment]
These are the musicians'.  Probably want to get a couple more (or tell me where they live if we already have extras).  I looked around under the sound board and in the supply closet.

If you can get them, that would be great.  Thanks!

**Comment by michellestith** [comment]
I'm happy to purchase.
Are we talking headphones or earbuds?

**Comment by russell-taylor** [comment]
The broken ones were earbuds, and that seems to be what most performers prefer.

**Comment by russell-taylor** [comment]
@michellestith Were you able to get these ordered?

**Comment by russell-taylor** [comment]
@michellestith I haven't heard from you so will go ahead and order these.

**Comment by russell-taylor** [comment]
Shipping to my house to arrive by Saturday.  Should be able to bring on Sunday.

**Comment by russell-taylor** [comment]
@michellestith had already brought some before I purchased these.
