### ISSUE TITLE
New xlr  cables for woods

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#57]
We need a couple of long ones for the piano and whatever is needed

**Comment by russell-taylor** [comment]
Two new 25' cables have been ordered, to arrive at Stith residence by Wednesday.  @michellestith Can you bring them to Woods next week?  I'll be running sound at Pittsboro.

**Comment by russell-taylor** [comment]
@michellestith Did these arrive?

**Comment by michellestith** [comment]
I brought the cables  as well as one set of earbuds and some new Ethernet
patch cables to Woods on Sunday.  I had a beautiful email to you regarding
these but was interrupted and left it in my drafts folder. So sorry to
neglect you. No problem with having extra earbuds

**Comment by russell-taylor** [comment]
Glad to hear it.  Closing the issue since they have been delivered.  Thanks!
