### ISSUE TITLE
C guitar picks 3d printed

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#60]
Given that someone had cut up a plastic card to make a guitar pick, we probably want to have an infinite supply of them at each site.  Perhaps a good use for the small bits of leftover filament on my 3D printer.  Could be cool if they had a CCC logo on them.

**Comment by russell-taylor** [comment]
Printed 3 and will show to Curtis to see if they are serviceable.

**Comment by russell-taylor** [comment]
This turns out to be perhaps the world's most expensive way to get barely-usable guitar picks when time is taken into account.  Purchasing some to put onsite.

**Comment by michellestith** [comment]
Well, I hope you had fun trying! Thanks for supporting the musicians this
way.

**Comment by russell-taylor** [comment]
Definitely fun trying.  Got to try out my Elmers disappearing purple glue stick, which worked on 5 out of 6 of them...

**Comment by russell-taylor** [comment]
Delivered box of 100 to Pittsboro and gave another to Michelle for woods
