### ISSUE TITLE
New phone input cables

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#70]
Two RCA on one end 1/4" on the other. At least 3 feet long. Fit into phone with a case.

**Comment by russell-taylor** [comment]
Ordered for delivery to my house by Tuesday.  Should be able to bring to both locations over the next two weeks.

**Comment by russell-taylor** [comment]
At woods this goes to two 1/4 phono jacks rather than rca

**Comment by russell-taylor** [comment]
Damian is going to reroute the woods board and install the new cable there.

**Comment by michellestith** [comment]
Russ, are both of those going to the sound boards?  I need one more the FOH
at PBO where we have an audio only option for groups that just want music.
The one I have up there now doesn't fit with a case.  Can you add that to
your order, or order one more, or send the link, please?  I have bought
some before and they still didn't work, so would love to use your idea.
Thanks
Michelle

**Comment by russell-taylor** [comment]
I got one for each sound board.

If the FOH one can use two RCA jacks to connect to the system, I can get another just like the one I got (probably a longer cable).  I haven't checked to see how well the ones I got worked yet, but plan to do that this Sunday at Pittsboro.  I got the 6' version of https://smile.amazon.com/gp/product/B00LM2Y2U4/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 and they make 10' and 15' as well.  I'll be glad to order another one if these turn out to work and can fit into the FOH inputs.

**Comment by michellestith** [comment]
right, good catch.  I will look and see what the inputs are - doh!

**Comment by russell-taylor** [comment]
They need to be phono connections rather than rca for both systems

**Comment by russell-taylor** [comment]
Damian re-routed to use the aux in in Woods and is doing the same in Pittsboro.

@michellestith Let me know what plugs the FOH system needs for its input and I'll be glad to get some.
