### ISSUE TITLE
Wireless mouse for Mac for Propresenter

### ISSUE THREAD

**Issue by Seyahmit** [chatham-community-church/Worship#8]
Tim does not adapt to new technology very quickly and still wants a mouse to run propresenter.

**Comment by russell-taylor** [comment]
Is one that has a wireless dongle that plugs into USB okay, or do you need a bluetooth one to preserve our USB ports?

**Comment by Seyahmit** [comment]
Wireless dongle is okay.

**Comment by russell-taylor** [comment]
Purchased, to arrive by Wednesday.  Plan to bring with me to church on Sunday when I run sound.
